import {RoutesEnum} from "../../../shared/constants/routes";
import {CocktailResponse} from "./models";

const margarita = {
  "drinks": [
    {
      "idDrink": "11007",
      "strDrink": "Margarita",
      "strDrinkAlternate": null,
      "strTags": "IBA,ContemporaryClassic",
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": "Contemporary Classics",
      "strAlcoholic": "Alcoholic",
      "strGlass": "Cocktail glass",
      "strInstructions": "Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.",
      "strInstructionsES": null,
      "strInstructionsDE": "Reiben Sie den Rand des Glases mit der Limettenscheibe, damit das Salz daran haftet. Achten Sie darauf, dass nur der \u00e4u\u00dfere Rand angefeuchtet wird und streuen Sie das Salz darauf. Das Salz sollte sich auf den Lippen des Genie\u00dfers befinden und niemals in den Cocktail einmischen. Die anderen Zutaten mit Eis sch\u00fctteln und vorsichtig in das Glas geben.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Strofina il bordo del bicchiere con la fetta di lime per far aderire il sale.\r\nAvere cura di inumidire solo il bordo esterno e cospargere di sale.\r\nIl sale dovrebbe presentarsi alle labbra del bevitore e non mescolarsi mai al cocktail.\r\nShakerare gli altri ingredienti con ghiaccio, quindi versarli delicatamente nel bicchiere.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/5noda61589575158.jpg",
      "strIngredient1": "Tequila",
      "strIngredient2": "Triple sec",
      "strIngredient3": "Lime juice",
      "strIngredient4": "Salt",
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 1/2 oz ",
      "strMeasure2": "1/2 oz ",
      "strMeasure3": "1 oz ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": "https://commons.wikimedia.org/wiki/File:Klassiche_Margarita.jpg",
      "strImageAttribution": "Cocktailmarler",
      "strCreativeCommonsConfirmed": "Yes",
      "dateModified": "2015-08-18 14:42:59"
    },
    {
      "idDrink": "11118",
      "strDrink": "Blue Margarita",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Cocktail glass",
      "strInstructions": "Rub rim of cocktail glass with lime juice. Dip rim in coarse salt. Shake tequila, blue curacao, and lime juice with ice, strain into the salt-rimmed glass, and serve.",
      "strInstructionsES": null,
      "strInstructionsDE": "Den Rand des Cocktailglases mit Limettensaft einreiben. Den Rand in grobes Salz tauchen. Tequila, blauen Curacao und Limettensaft mit Eis sch\u00fctteln, in das mit Salz umh\u00fcllte Glas abseihen und servieren.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Strofinare il bordo del bicchiere da cocktail con succo di lime. Immergere il bordo nel sale grosso. Shakerare tequila, blue curacao e succo di lime con ghiaccio, filtrare nel bicchiere bordato di sale e servire.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/bry4qh1582751040.jpg",
      "strIngredient1": "Tequila",
      "strIngredient2": "Blue Curacao",
      "strIngredient3": "Lime juice",
      "strIngredient4": "Salt",
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 1/2 oz ",
      "strMeasure2": "1 oz ",
      "strMeasure3": "1 oz ",
      "strMeasure4": "Coarse ",
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "Yes",
      "dateModified": "2015-08-18 14:51:53"
    },
    {
      "idDrink": "17216",
      "strDrink": "Tommy's Margarita",
      "strDrinkAlternate": null,
      "strTags": "IBA,NewEra",
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": "New Era Drinks",
      "strAlcoholic": "Alcoholic",
      "strGlass": "Old-Fashioned glass",
      "strInstructions": "Shake and strain into a chilled cocktail glass.",
      "strInstructionsES": null,
      "strInstructionsDE": "Sch\u00fctteln und in ein gek\u00fchltes Cocktailglas abseihen.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Shakerare e filtrare in una coppetta da cocktail ghiacciata.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/loezxn1504373874.jpg",
      "strIngredient1": "Tequila",
      "strIngredient2": "Lime Juice",
      "strIngredient3": "Agave syrup",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "4.5 cl",
      "strMeasure2": "1.5 cl",
      "strMeasure3": "2 spoons",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2017-09-02 18:37:54"
    },
    {
      "idDrink": "16158",
      "strDrink": "Whitecap Margarita",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Other / Unknown",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Margarita/Coupette glass",
      "strInstructions": "Place all ingredients in a blender and blend until smooth. This makes one drink.",
      "strInstructionsES": null,
      "strInstructionsDE": "Alle Zutaten in einen Mixer geben und mischen.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Metti tutti gli ingredienti in un frullatore e frulla fino a che non diventa liscio.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/srpxxp1441209622.jpg",
      "strIngredient1": "Ice",
      "strIngredient2": "Tequila",
      "strIngredient3": "Cream of coconut",
      "strIngredient4": "Lime juice",
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 cup ",
      "strMeasure2": "2 oz ",
      "strMeasure3": "1/4 cup ",
      "strMeasure4": "3 tblsp fresh ",
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2015-09-02 17:00:22"
    },
    {
      "idDrink": "12322",
      "strDrink": "Strawberry Margarita",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Cocktail glass",
      "strInstructions": "Rub rim of cocktail glass with lemon juice and dip rim in salt. Shake schnapps, tequila, triple sec, lemon juice, and strawberries with ice, strain into the salt-rimmed glass, and serve.",
      "strInstructionsES": null,
      "strInstructionsDE": "Cocktailglasrand mit Zitronensaft und Tauchrand in Salz wenden. Schnaps, Tequila, Triple-Sec, Zitronensaft und Erdbeeren mit Eis sch\u00fctteln, in das salzige Glas sieben und servieren.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Strofinare il bordo del bicchiere da cocktail con succo di limone e immergerlo nel sale. Shakerare grappa, tequila, triple sec, succo di limone e fragole con ghiaccio, filtrare nel bicchiere bordato di sale e servire.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/tqyrpw1439905311.jpg",
      "strIngredient1": "Strawberry schnapps",
      "strIngredient2": "Tequila",
      "strIngredient3": "Triple sec",
      "strIngredient4": "Lemon juice",
      "strIngredient5": "Strawberries",
      "strIngredient6": "Salt",
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1/2 oz ",
      "strMeasure2": "1 oz ",
      "strMeasure3": "1/2 oz ",
      "strMeasure4": "1 oz ",
      "strMeasure5": "1 oz ",
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2015-08-18 14:41:51"
    },
    {
      "idDrink": "178332",
      "strDrink": "Smashed Watermelon Margarita",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Cocktail",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Collins glass",
      "strInstructions": "In a mason jar muddle the watermelon and 5 mint leaves together into a puree and strain. Next add the grapefruit juice, juice of half a lime and the tequila as well as some ice. Put a lid on the jar and shake. Pour into a glass and add more ice. Garnish with fresh mint and a small slice of watermelon.",
      "strInstructionsES": null,
      "strInstructionsDE": null,
      "strInstructionsFR": null,
      "strInstructionsIT": "In un barattolo di vetro pestare l'anguria e 5 foglie di menta insieme, filtrare il contenuto in un bicchiere. Quindi aggiungere il succo di pompelmo, il succo di mezzo lime, la tequila e un po 'di ghiaccio. Metti un coperchio sul barattolo e agita. Versare in un bicchiere e aggiungere altro ghiaccio. Guarnire con menta fresca e una fettina di anguria.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/dztcv51598717861.jpg",
      "strIngredient1": "Watermelon",
      "strIngredient2": "Mint",
      "strIngredient3": "Grapefruit Juice",
      "strIngredient4": "Lime",
      "strIngredient5": "Tequila",
      "strIngredient6": "Watermelon",
      "strIngredient7": "Mint",
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1/2 cup",
      "strMeasure2": "5",
      "strMeasure3": "1/3 Cup",
      "strMeasure4": "Juice of 1/2",
      "strMeasure5": "1 shot",
      "strMeasure6": "Garnish with",
      "strMeasure7": "Garnish with",
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": null
    }
  ]
}

const kir = {
  "drinks": [
    {
      "idDrink": "17203",
      "strDrink": "Kir",
      "strDrinkAlternate": null,
      "strTags": "IBA,ContemporaryClassic",
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Wine Glass",
      "strInstructions": "Add the cr\u00e8me de cassis to the bottom of the glass, then top up with wine.",
      "strInstructionsES": null,
      "strInstructionsDE": "Gib die Creme de Cassis auf den Boden des Glases und f\u00fcge dann Wein hinzu.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Aggiungere la cr\u00e8me de cassis sul fondo del bicchiere, quindi rabboccare con il vino.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/apneom1504370294.jpg",
      "strIngredient1": "Creme de Cassis",
      "strIngredient2": "Champagne",
      "strIngredient3": null,
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 part ",
      "strMeasure2": "5 parts ",
      "strMeasure3": null,
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2017-09-02 17:38:14"
    },
    {
      "idDrink": "13837",
      "strDrink": "Kir Royale",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Champagne Flute",
      "strInstructions": "Pour Creme de cassis in glass, gently pour champagne on top",
      "strInstructionsES": null,
      "strInstructionsDE": "Creme de Cassis in ein Glas geben, vorsichtig Champagner dar\u00fcber gie\u00dfen.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Versare la Creme de cassis nel bicchiere, versai sopra delicatamente lo champagne",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/yt9i7n1504370388.jpg",
      "strIngredient1": "Creme de Cassis",
      "strIngredient2": "Champagne",
      "strIngredient3": null,
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 part ",
      "strMeasure2": "5 parts ",
      "strMeasure3": null,
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2017-09-02 17:39:48"
    },
    {
      "idDrink": "11433",
      "strDrink": "Grass Skirt",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Old-fashioned glass",
      "strInstructions": "In a shaker half-filled with ice cubes, combine the gin, triple sec, pineapple juice, and grenadine. Shake well. Pour into an old-fashioned glass and garnish with the pineapple slice.",
      "strInstructionsES": "En una coctelera llena hasta la mitad con cubitos de hielo, mezcle la ginebra, el triple sec, el zumo de pi\u00f1a y la granadina. Agitar bien. Verter en un vaso old fashioned y decorar con la rodaja de pi\u00f1a.",
      "strInstructionsDE": "In einem Shaker, der halb mit Eisw\u00fcrfel gef\u00fcllt ist, den Gin, die Triple Sec, Ananassaft und Grenadine miteinander vermengen. Gut sch\u00fctteln. In ein old-fashioned Glas geben und mit der Ananasscheibe garnieren.",
      "strInstructionsFR": "Dans un shaker \u00e0 moiti\u00e9 rempli de gla\u00e7ons, m\u00e9langer le gin, le triple sec, le jus d'ananas et la grenadine. Bien agiter. Verser dans un verre \u00e0 l'ancienne et d\u00e9corer avec la tranche d'ananas.",
      "strInstructionsIT": "In uno shaker riempito a met\u00e0 con cubetti di ghiaccio, unisci il gin, il triple sec, il succo d'ananas e la granatina, versare in un bicchiere vecchio stile e guarnire con la fetta di ananas. Agitare bene",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/qyvprp1473891585.jpg",
      "strIngredient1": "Gin",
      "strIngredient2": "Triple sec",
      "strIngredient3": "Pineapple juice",
      "strIngredient4": "Grenadine",
      "strIngredient5": "Pineapple",
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 1/2 oz ",
      "strMeasure2": "1 oz ",
      "strMeasure3": "1 oz ",
      "strMeasure4": "1/2 tsp ",
      "strMeasure5": "1 ",
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2016-09-14 23:19:46"
    }
  ]
}

const a1 = {
  "drinks": [
    {
      "idDrink": "17222",
      "strDrink": "A1",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Cocktail",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Cocktail glass",
      "strInstructions": "Pour all ingredients into a cocktail shaker, mix and serve over ice into a chilled glass.",
      "strInstructionsES": "Verter todos los ingredientes en una coctelera, mezclar y servir con hielo en una copa fr\u00eda.",
      "strInstructionsDE": "Alle Zutaten in einen Cocktailshaker geben, mischen und \u00fcber Eis in ein gek\u00fchltes Glas servieren.",
      "strInstructionsFR": "Verser tous les ingr\u00e9dients dans un shaker, m\u00e9langer et servir avec des gla\u00e7ons dans un verre r\u00e9frig\u00e9r\u00e9.",
      "strInstructionsIT": "Versare tutti gli ingredienti in uno shaker, mescolare e servire con ghiaccio in un bicchiere freddo.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg",
      "strIngredient1": "Gin",
      "strIngredient2": "Grand Marnier",
      "strIngredient3": "Lemon Juice",
      "strIngredient4": "Grenadine",
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 3/4 shot ",
      "strMeasure2": "1 Shot ",
      "strMeasure3": "1/4 Shot",
      "strMeasure4": "1/8 Shot",
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2017-09-07 21:42:09"
    }
  ]
}

const mojito = {
  "drinks": [
    {
      "idDrink": "11000",
      "strDrink": "Mojito",
      "strDrinkAlternate": null,
      "strTags": "IBA,ContemporaryClassic,Alcoholic,USA,Asia,Vegan,Citrus,Brunch,Hangover,Mild",
      "strVideo": null,
      "strCategory": "Cocktail",
      "strIBA": "Contemporary Classics",
      "strAlcoholic": "Alcoholic",
      "strGlass": "Highball glass",
      "strInstructions": "Muddle mint leaves with sugar and lime juice. Add a splash of soda water and fill the glass with cracked ice. Pour the rum and top with soda water. Garnish and serve with straw.",
      "strInstructionsES": "Mezcle las hojas de menta con el az\u00facar y el zumo de lima. A\u00f1ada un chorrito de soda y llene el vaso con hielo picado. Verter el ron y completar con soda. Decorar y servir con pajita.",
      "strInstructionsDE": "Minzbl\u00e4tter mit Zucker und Limettensaft verr\u00fchren. F\u00fcge einen Spritzer Sodawasser hinzu und f\u00fclle das Glas mit gebrochenem Eis. Den Rum eingie\u00dfen und mit Sodawasser \u00fcbergie\u00dfen. Garnieren und mit einem Strohhalm servieren.",
      "strInstructionsFR": "M\u00e9langer les feuilles de menthe avec le sucre et le jus de citron vert. Ajoutez un filet d'eau gazeuse et remplissez le verre de glace concass\u00e9e. Verser le rhum et compl\u00e9ter avec de l'eau gazeuse. D\u00e9corer et servir avec une paille.",
      "strInstructionsIT": "Pestare le foglie di menta con lo zucchero e il succo di lime.\r\nAggiungere una spruzzata di acqua di seltz e riempi il bicchiere con ghiaccio tritato.\r\nVersare il rum e riempire con acqua di seltz.\r\nGuarnire con una fetta di lime, servire con una cannuccia.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/metwgh1606770327.jpg",
      "strIngredient1": "Light rum",
      "strIngredient2": "Lime",
      "strIngredient3": "Sugar",
      "strIngredient4": "Mint",
      "strIngredient5": "Soda water",
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "2-3 oz ",
      "strMeasure2": "Juice of 1 ",
      "strMeasure3": "2 tsp ",
      "strMeasure4": "2-4 ",
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": "https://pixabay.com/photos/cocktail-mojito-cocktail-recipe-5096281/",
      "strImageAttribution": "anilaha https://pixabay.com/users/anilaha-16242978/",
      "strCreativeCommonsConfirmed": "Yes",
      "dateModified": "2016-11-04 09:17:09"
    },
    {
      "idDrink": "15841",
      "strDrink": "Mojito Extra",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Cocktail",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Collins glass",
      "strInstructions": "Put mint with lemon juice in a glas, mash the mint with a spoon, ice, rum & fill up with club soda. Top it with Angostura.",
      "strInstructionsES": "Ponga menta con zumo de lim\u00f3n en un vaso, machaque la menta con una cuchara, hielo, ron y rellene con club soda. A\u00f1ada Angostura.",
      "strInstructionsDE": "Minze mit Zitronensaft in ein Glas geben, Minze mit einem L\u00f6ffel zerdr\u00fccken. Eis und Rum hinzuf\u00fcgen und mit Soda auff\u00fcllen. Kr\u00f6nen Sie es mit Angostura.",
      "strInstructionsFR": "Mettre de la menthe et du jus de citron dans un verre, \u00e9craser la menthe avec une cuill\u00e8re, de la glace, du rhum et compl\u00e9ter avec du club soda. Compl\u00e9ter avec de l'Angostura.",
      "strInstructionsIT": "Metti la menta con il succo di limone in un bicchiere, schiaccia la menta con un cucchiaio, ghiaccio, rum e riempila con la soda.\r\nCompletalo con Angostura.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vwxrsw1478251483.jpg",
      "strIngredient1": "Mint",
      "strIngredient2": "Lemon juice",
      "strIngredient3": "Dark rum",
      "strIngredient4": "Club soda",
      "strIngredient5": "Angostura bitters",
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1/2 handful ",
      "strMeasure2": "3 cl ",
      "strMeasure3": "1/8 L Jamaican ",
      "strMeasure4": "1/8 L ",
      "strMeasure5": "8 drops ",
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2016-11-04 09:24:43"
    },
    {
      "idDrink": "178358",
      "strDrink": "Mango Mojito",
      "strDrinkAlternate": null,
      "strTags": "Fruity",
      "strVideo": null,
      "strCategory": "Cocktail",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Jar",
      "strInstructions": "Squeeze the juice from 1\u00bd limes and blend with the mango to give a smooth pur\u00e9e.\nCut the rest of the limes into quarters, and then cut each wedge in half again. Put 2 pieces of lime in a highball glass for each person and add 1 teaspoon of caster sugar and 5-6 mint leaves to each glass. Squish everything together with a muddler or the end of a rolling pin to release all the flavours from the lime and mint.\nDivide the mango pur\u00e9e between the glasses and add 30ml white rum and a handful of crushed ice to each one, stirring well to mix everything together. Top up with soda water to serve and garnish with extra mint, if you like.",
      "strInstructionsES": "Exprimir el zumo de 1\u00bd limas y mezclarlo con el mango para obtener un pur\u00e9 suave.\r\nCorte el resto de las limas en cuartos y, a continuaci\u00f3n, vuelva a cortar cada gajo por la mitad. Ponga 2 trozos de lima en un vaso alto para cada persona y a\u00f1ada 1 cucharadita de az\u00facar glas y 5-6 hojas de menta a cada vaso. Apl\u00e1stelo todo con un batidor o con la punta de un rodillo para liberar todos los sabores de la lima y la menta.\r\nDivida el pur\u00e9 de mango entre los vasos y a\u00f1ada 30 ml de ron blanco y un pu\u00f1ado de hielo picado a cada uno, removiendo bien para mezclarlo todo. Completar con agua con gas para servir y decorar con m\u00e1s menta, si se desea.",
      "strInstructionsDE": "Den Saft von 1\u00bd Limetten auspressen und mit der Mango zu einem glatten P\u00fcree vermischen.",
      "strInstructionsFR": "Presser le jus de 1\u00bd citron vert et le mixer avec la mangue pour obtenir une pur\u00e9e lisse.\nCouper le reste des citrons verts en quatre, puis couper \u00e0 nouveau chaque quartier en deux. Mettez 2 morceaux de citron vert dans un verre highball pour chaque personne et ajoutez 1 cuill\u00e8re \u00e0 caf\u00e9 de sucre en poudre et 5-6 feuilles de menthe dans chaque verre. Pressez le tout \u00e0 l'aide d'un mixeur ou de l'extr\u00e9mit\u00e9 d'un rouleau \u00e0 p\u00e2tisserie pour lib\u00e9rer tous les ar\u00f4mes du citron vert et de la menthe.\nR\u00e9partissez la pur\u00e9e de mangue dans les verres et ajoutez 30 ml de rhum blanc et une poign\u00e9e de glace pil\u00e9e dans chacun d'eux, en remuant bien pour m\u00e9langer le tout. Compl\u00e9tez avec de l'eau gazeuse pour servir et d\u00e9corez avec de la menthe suppl\u00e9mentaire, si vous le souhaitez.",
      "strInstructionsIT": "Spremete il succo di 1 lime e mezzo e frullatelo con il mango per ottenere una purea omogenea.\nTagliare il resto dei lime in quarti, quindi tagliare nuovamente ogni spicchio a met\u00e0. Metti 2 pezzi di lime in un bicchiere highball per ogni persona e aggiungi 1 cucchiaino di zucchero semolato e 5-6 foglie di menta in ogni bicchiere. Schiacciate il tutto con un pestello o con l'estremit\u00e0 di un mattarello per far sprigionare tutti i sapori del lime e della menta.\nDividete la purea di mango nei bicchieri e aggiungete in ognuno 30 ml di rum bianco e una manciata di ghiaccio tritato, mescolando bene per amalgamare il tutto. Rabboccare con acqua gassata per servire e guarnire con menta extra, se lo si desidera.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/wfqmgm1630406820.jpg",
      "strIngredient1": "Lime",
      "strIngredient2": "Mango",
      "strIngredient3": "Mint",
      "strIngredient4": "White Rum",
      "strIngredient5": "Ice",
      "strIngredient6": "Soda Water",
      "strIngredient7": "Mango",
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "3",
      "strMeasure2": "1 Fresh",
      "strMeasure3": "Sprig",
      "strMeasure4": "200 ml",
      "strMeasure5": "cubes",
      "strMeasure6": "Top",
      "strMeasure7": "Garnish with",
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": "https://www.instagram.com/p/COVlG8TMZYU",
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": null
    },
    {
      "idDrink": "178336",
      "strDrink": "Blueberry Mojito",
      "strDrinkAlternate": null,
      "strTags": "Fruity",
      "strVideo": null,
      "strCategory": "Cocktail",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Highball glass",
      "strInstructions": "Muddle the blueberries with the other ingredients and serve in a highball glass. Garnish with mint and a half slice of lime.",
      "strInstructionsES": "Mezcla los ar\u00e1ndanos con los dem\u00e1s ingredientes y s\u00edrvelo en un vaso highball. Decorar con menta y media rodaja de lima.",
      "strInstructionsDE": null,
      "strInstructionsFR": "M\u00e9langer les myrtilles avec les autres ingr\u00e9dients et servir dans un verre highball. Garnir de menthe et d'une demi-tranche de citron vert.",
      "strInstructionsIT": "Pestare i mirtilli con gli altri ingredienti e servire in un bicchiere highball. Guarnire con la menta e mezza fetta di lime.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/07iep51598719977.jpg",
      "strIngredient1": "Dark Rum",
      "strIngredient2": "Lime Juice",
      "strIngredient3": "Sugar",
      "strIngredient4": "Blueberries",
      "strIngredient5": "Lemon-lime soda",
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "2 shots",
      "strMeasure2": "1 shot",
      "strMeasure3": "Dash",
      "strMeasure4": "Whole",
      "strMeasure5": "Top",
      "strMeasure6": "",
      "strMeasure7": "",
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": null
    }
  ]
}

export const mockCocktails: Record<RoutesEnum, CocktailResponse> = {
  [RoutesEnum.Margarita]: margarita,
  [RoutesEnum.Mojito]: mojito,
  [RoutesEnum.A1]: a1,
  [RoutesEnum.Kir]: kir,
}
